# Generated by Django 4.2.6 on 2023-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.png", upload_to="profile_pictures"
            ),
        ),
    ]
