# Generated by Django 4.2.6 on 2023-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calificami", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="course",
            field=models.CharField(default="ninguno", max_length=30),
        ),
    ]
